//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale.Domain.Query.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public long Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public long ProductId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
