//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Framework.Data;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Sale.Domain.Query.Model
{

    public partial class SaleEntities : IDbContext
    {
        public Task BeginAsync()
        {
            throw new System.NotImplementedException();
        }

        public Task CommitAsync()
        {
            throw new System.NotImplementedException();
        }

        public Task<int> SaveChangesAsync()
        {
            throw new System.NotImplementedException();
        }

        public Task RollbackAsync()
        {
            throw new System.NotImplementedException();
        }

        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderLine> OrderLines { get; set; }
    }
}
